AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

Naming/FileName:
  Exclude:
    - 'lib/legionio-spec.rb'

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ModuleLength:
  Max: 1500

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150
